config/routes.rb
Rails.application.routes.draw do

  root to: 'addresses#index'

  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :addresses do
    collection do
      get 'cep/:cep', action: 'address_by_cep', defaults: { format: 'json' }
      get 'by_cep/', action: 'list_by_cep'
    end
  end

  scope :admin do
    resources :users, only: [:show, :index, :destroy], controller: 'admin/users'
  end
end

app/models/address.rb
class Address < ApplicationRecord

  #TODO: Improve this code
  def self.by_cep(cep)
    provider = [ViacepService, PostmonService].sample.new
    address_attrs = provider.get(cep)

    return nil if address_attrs.include? :error

    Address.new(address_attrs)
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable,
  # :recoverable, :rememberable, :trackable, :validatable and :omniauthable
  devise :database_authenticatable, :registerable
end

app/controllers/addresses_controller.rb
class AddressesController < ApplicationController
  before_action :authenticate_user!

  def index
    @addresses = Address.all
  end

  # POST /addresses/create
  def create
    @address = Address.create(address_params)
    redirect_to address_path(@address)
  end

  # GET /addresses/new
  def new
    @address = Address.new
  end

  def show
    @address = Address.find(id)
  end

  def list_by_cep
    @addresses = Address.where(zipcode: cep)
    render :index
  end

  def address_by_cep
    @address = Address.by_cep(cep)
    render json: @address
  end

  private

  def address_params
    #TODO: Add filter to zipcode returns only digits. See #cep
    params.require(:address).permit(
      :neighborhood,
      :street,
      :city,
      :state,
      :number,
      :zipcode,
      :complement
    )
  end

  def id
    params.require(:id)
  end

  def cep
    params.require(:cep).scan(/\d/).join('')
  end
end

app/controllers/admin/users_controller.rb
module Admin
  class UsersController < ApplicationController
    before_action :load_user, only: [:destroy]

    def index
      @users = User.all
    end

    def destroy
      @user.destroy

      redirect_to users_path
    end

    private

    def load_user
      @user = User.find(id)
    end

    def id
      params.require(:id)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
# before_action :configure_sign_up_params, only: [:create]
# before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
# before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/addresses/_form.html.erb
<%= simple_form_for address, html: { class: 'form-horizontal'} do |f| %>
  <%= f.input :zipcode, label: false, placeholder: 'CEP', required: true  %><!-- <a href='#' onclick='autoFill'>Auto preencher</a> -->
  <%= f.input :street, label: false, placeholder: 'Logradouro', required: true   %>
  <%= f.input :neighborhood, label: false, placeholder: 'Bairro' %>
  <%= f.input :city, label: false, placeholder: 'Cidade' %>
  <%= f.input :state, label: false, placeholder: 'UF' %>
  <%= f.input :number, label: false, placeholder: 'numero', required: true   %>
  <%= f.input :complement, label: false, placeholder: 'Complemento' %>

  <%= f.button :submit, class: 'btn btn-success' %>
<% end %>

app/views/addresses/index.html.erb
  <%# TODO: Change this form to uses AJAX/remote %>
  <%= form_tag "/addresses/by_cep", method: :get, class: 'form-inline' do |f| %>
    <div class='row'>
      <div class='form-group col-md-12'>
        <%= text_field_tag :cep, "", placeholder: "Busca de endereços por CEP", class: 'form-control' %>

        <%= submit_tag "Buscar", class: 'btn btn-primary' %>
      </div>
    </div>
  <% end %>

<div>
  <% @addresses.each do |address| %>
    <p>
      <%= address.street %>, <%= address.number %> - <%= address.city %>
    </p>
  <% end %>
</div>

app/views/addresses/new.html.erb
<div class='col-md-6 col-xs-6'>
  <%= render partial: 'form', locals: { address: @address } %>
</div>

app/views/addresses/show.html.erb
<h3> Address </h3>

<p>
  <%= @address.street %>, <%= @address.number %> - <%= @address.complement %>
  <br />
  <%= @address.neighborhood %>, <%= @address.city %> - <%= @address.state %> - CEP <%= @address.zipcode %>
</p>

app/views/admin/users/index.html.erb
<table>
  <tr>
    <th> # </th>
    <th> e-mail </th>
    <th> Ações </th>
  </tr>

  <% @users.each do |user| %>
    <tr>
      <td><%= user.id %></td>
      <td><%= user.email %></td>
      <td><%= button_to "apagar", user_path(user), :method => :delete %></td>
    </tr>
  <% end %>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Gokucommerce</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div id='stage' class='container'>
      <%= render 'shareds/topmenu' %>

      <div class='row col-md-offset-2 col-xs-offset-2' id='main' style='margin-top: 60px;'>
        <%= yield %>
      </div>
    </div>
  </body>
</html>

app/views/shareds/_topmenu.html.erb
<div id='top-head' class='row'>
  <!-- Top Menu -->
  <nav class='navbar navbar-inverse navbar-fixed-top' role='navigation'>
    <div class='container-fluid'>
      <!-- Menu que deveria aparecer no Mobile -->
      <% # Porém não tá rolando essas classes do tbs e não posso perder tempo com isso %>
      <div class='navbar-header'>
        <button type='button'
          class='navbar-toggle collapsed'
          data-toggle='collapse'
          data-target='#navbar'
          aria-expanded='false'
          aria-controls='navbar'
          >
          <span class='sr-only'>Menu</span>
          <% 3.times.each do %>
            <span class='icon-bar'></span>
          <% end %>
        </button>
        <!-- /button menu -->
        <a class="navbar-brand" href="#">Goku Commerce</a>
      </div> <!--/navbar-header-->

      <div id='navbar' class='navbar-collapse collapse' aria-expanded='true' style='height: 1px;'>
        <ul class='nav navbar-nav'>
          <li>
            <a href="/">Home</a>
          </li>
          <li>
            <%= link_to "Novo", new_address_path %>
          </li>
        </ul><!--/ul-->
      </div><!--/#navbar-->
    </div>
  </nav>
  <!-- /Top Menu -->
</div>